### ISSUE TITLE
Unexpected error: Cannot find module 'invariant'

### ISSUE THREAD

**Issue by atmoner** [neonious/lowjs#125]
Hello,
I have a problem when I try to send a script to my card:

![image](https://user-images.githubusercontent.com/1071490/106037164-36920200-60ce-11eb-8048-545f8951e610.png)

```
┌─[✗]─[atmon3r@atmon3r-pc]─[~/Desktop/esp32Js]
└──╼ $lowsync sync
Fetching file system listings...
Reminder: No password set! Please set one via the lowsync settings set web.password="..." command. Continuing...
Preparing synchronization... |░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░| 0%{file}Unexpected error: Cannot find module 'invariant'
Require stack:
- /home/atmon3r/.nvm/versions/node/v12.18.3/lib/node_modules/lowsync/build/index.js Error: Cannot find module 'invariant'
Require stack:
- /home/atmon3r/.nvm/versions/node/v12.18.3/lib/node_modules/lowsync/build/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.invariant (/home/atmon3r/.nvm/versions/node/v12.18.3/lib/node_modules/lowsync/build/webpack:/external "invariant":1:1)
    at __webpack_require__ (/home/atmon3r/.nvm/versions/node/v12.18.3/lib/node_modules/lowsync/build/webpack:/webpack/bootstrap:25:1)
    at Object../node_modules/@babel/preset-env/lib/utils.js (/home/atmon3r/.nvm/versions/node/v12.18.3/lib/node_modules/lowsync/build/webpack:/node_modules/@babel/preset-env/lib/utils.js:25)
    at __webpack_require__ (/home/atmon3r/.nvm/versions/node/v12.18.3/lib/node_modules/lowsync/build/webpack:/webpack/bootstrap:25:1)
    at Object../node_modules/@babel/preset-env/lib/debug.js (/home/atmon3r/.nvm/versions/node/v12.18.3/lib/node_modules/lowsync/build/webpack:/node_modules/@babel/preset-env/lib/debug.js:10)
    at __webpack_require__ (/home/atmon3r/.nvm/versions/node/v12.18.3/lib/node_modules/lowsync/build/webpack:/webpack/bootstrap:25:1)
```

I tried to install the package invariant but it doesn't change anything

thank you in advance

**Comment by atmoner** [comment]
It's ok! Fixed on change `transpile` to false in `lowsync.config.json`, like this:

```
{
    "ip": "192.168.1.18",
    "transpile": false
}
```
