### ISSUE TITLE
Install issue Linux Mint 18.3.

### ISSUE THREAD

**Issue by CelliesProjects** [neonious/lowjs#58]
Howdy,
I had some serious issues with the nodejs and npm install just to get as far as I got.
That was some serious digging. 
Anyway, now I am at the stage where I try to install lowsync and get this error:
````
lowsync flash /dev/ttyUSB0 --init

/usr/local/lib/node_modules/lowsync/build/index.js:177
        Object.setPrototypeOf(this, new.target.prototype); // restore prototype chain
                                       ^
SyntaxError: Unexpected token .
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
````
Nodejs is at v4.2.6.
Npm is at 3.5.2.

**Comment by CelliesProjects** [comment]
Never mind, compiling from source solved it..
